### ISSUE TITLE
[database] Plan a migration process for the DB

### ISSUE THREAD

**Issue by frgfm** [pyronear/pyro-api#107]
There is no migration process with FastAPI or SQLAlchemy by default, we need to investigate our options here.

**Comment by chloeskt** [comment]
I've heard about this library, might be useful https://alembic.sqlalchemy.org/en/latest/tutorial.html

**Comment by florianriche** [comment]
Indeed, for an example of the integration of alembic with FastAPI, the FastAPI creator used it for the fullstack template: https://github.com/tiangolo/full-stack-fastapi-postgresql

**Comment by frgfm** [comment]
If tiangolo uses it, that might be a good option :+1: 
Anyone fancies trying her/his luck with a PR?

**Comment by jeanpasquier75** [comment]
Created a dedicated branch [dbmigration-alembic](https://github.com/pyronear/pyro-api/tree/dbmigration-alembic), not ready yet for a PR I guess. Can you please have a look @chloeskt @florianriche  ? Especially you @frgfm since it concerns chore features !

**Comment by frgfm** [comment]
@jeanpasquier75 Sure, would you have the ref to the specific modules you made your branch after? I have no experience with alembic so it's hard for me to compare :sweat_smile:

**Comment by frgfm** [comment]
When you have some free time, it would be awesome to get this PR ready @jeanpasquier75 :grin:
