### ISSUE TITLE
[risk] How to update & store risk

### ISSUE THREAD

**Issue by jean-pasquier** [pyronear/pyro-api#108]
How to:

* trigger pyro-risk update (at a daily basis with current data source)
* store the results: where, how long, who can have access, etc.
* orchestrate pyro-platform <-> pyro-api <-> pyro-risk

Need to coordinate with all teams

**Comment by frgfm** [comment]
For a reason of security & load management, I think external services should have their own API (they wouldn't be deployed on the same instance either way). This repo is about wildfire alert, we can have one about image analysis, about data curation, etc.

If authentication is required (like in the alert monitoring platform):
- either we centralize authentication through this API
- or we make the services completely independent (I would recommend this one)

Either way, I'd argue this repo shouldn't open API access to other services. It's the most critical one (used by firefighters in delicate situations), so it should have the highest priority :ok_hand: 
So I'll close this issue, feel free to reopen if needed :)
