### ISSUE TITLE
[client][devices] multiple devices and one onlye exposed to the internet 

### ISSUE THREAD

**Issue by fe51** [pyronear/pyro-api#136]
## Feature 

Have a convenient solution available to communicate from site

## Motivation

For a site equipped with the Pyronear solution, we are going to have several devices with camera, and one central device performing the inference (connected on a local network). So, only one device, the one doing inference will be exposed to the internet (for security aspects, in order to avoir entry points into our system, and to limit the number of actions to be carried out on devices with camera which will be exposed to sun and subject to quite high level of temperature) 

Thus, only this one with communicate through the api and we need to be able to handle communication smoothly (that is to say, to be able to correctly route alerts from various devices with only one device using the api client).

2 possible solutions seem feasible :

- The central device has credentials of all other devices, hence, via the api client, creation of one class per camera devices and authenticate for each camera, then it should be possible to manage classes and properly route communication. 
  It's a bit DIY though, and not very practical  as the api is supposed to be able to facilitate the communication of devices.

- Some evolution are performed on the api, in order to manager a group of devices on a site, with only one connected to the internet, and with a unique authentification. 

What do you think @florianriche @jeanpasquier75 @frgfm ? There might be other ways to solve this issue.
I will be happy to discuss this, and organizing a quick meeting if necessary. Do not hesitate if you want me to clarify the issue !

**Comment by frgfm** [comment]
Hi @fe51 !

Thanks for the issue! I may not have all the information required to answer properly but here is my take on this:

### General design
We've been quite busy this week addressing several backend modifications :sweat_smile: 
While we have always thought about a solution where 1 raspberry/device would be connected to several cameras, this option of having several devices but 1 connected to the internet is rather recent. So for me, there are three things to address upfront:
1 - Taking all technical constraints from the different teams, is this the best solution?
2 - If so, do we have all the constraints/information to consider this decision final?
3 - from now one, is this the direction of the hardware solution? (is this suitable for more use cases? the non-equal connectivity of the solution is really raising concerns for me personally: having multiple cameras )

### Backend support
I cannot speak for the whole team, but at least I see a few constraints here:
- **security**: we have to minimize our exposure to vulnerability _(I admit that pure independence of devices would help quite a lot)_
- **connection reliability**: having multiple cameras connected with wires to a device accessing the internet is very different in terms of reliability of having a local network of devices with a single one entrusted with connectivity.
- **signing each alert/picture**: whatever the implementation, if a picture is taken, we need to be able to access the orientation of the camera, its position, and its registered device.

Now, back to implementation suggestion, considering everything above:
- we cannot have "camera raspberry" being considered by the API as the same as the one connected to the internet (cf. signing)
- having a raspberry accessing the API on behalf of another device is technically possible, but it means having ALL the information of several devices sent properly. And it means that the credentials to other devices would be stored on one of them (cf. security)

What do you think @pyronear/back-end @pyronear/hardware ?

**Comment by frgfm** [comment]
If we move forward with the option of having multiple API client instances (one for each camera device) in the central device, I think we can close this issue. The client is already access-specific (here device-specific) and thus there is no need for further modifications. What do you think @fe51 ?

**Comment by frgfm** [comment]
Closing this as the consequent PRs do not involve this repo :) 
Feel free to reopen if I'm wrong about this!
