### ISSUE TITLE
[scope] The "me" scope is supposedly useless

### ISSUE THREAD

**Issue by frgfm** [pyronear/pyro-api#139]
Having refactored most of the unittests, I came to the conclusion that the "me" scope is useless. 

Simply put, here is a route using it now:
```
@router.get("/me", response_model=UserRead, summary="Get information about the current user")
async def get_my_user(me: UserRead = Security(get_current_user, scopes=["admin", "me"])):
    """
    Retrieves information about the current user
    """
    return me
```

Now if we use the `user` scope instead:
```
@router.get("/me", response_model=UserRead, summary="Get information about the current user")
async def get_my_user(me: UserRead = Security(get_current_user, scopes=["admin", "user"])):
    """
    Retrieves information about the current user
    """
    return me
```
assuming all entries in the user table with "me" will be replaced by "user", we get the exact same behaviour. 

There is no difference in "access level" between a "user" and "me" (or "device" and "me" depending on the situation). So I suggest that we remove it to avoid unnecessary complication. We will have to discuss access levels later on to distinguish a bare user from a "supervisor" or a "manager".

I suggest waiting for #138 approval before starting a PR to avoid conflicts.

**Comment by fe51** [comment]
Hey !
Stupid question to begin, so far,  do we have a scope 'user' ?

in deps
```
# Scope definition
oauth2_scheme = OAuth2PasswordBearer(
    tokenUrl="login/access-token",
    scopes={
        "me": "Read information about the current user.",
        "admin": "Admin rights on all routes.",
        "device": "Send heartbeat signal and media to the API for only one device"
    }
)
 ```

**Comment by frgfm** [comment]
Now that the test refactoring is merged, I have a few PRs to push, including the one for the "me" scope. And in this PR, yes, I noticed the user scope is not defined in oauth2_scheme :upside_down_face:

**Comment by fe51** [comment]
Okay, seems to be it is jut to have a more "compliant" naming with oauth2 scheme ! I might have mis somthing but I am okay !
