### ISSUE TITLE
[alerts] Add a callback on alert creation to provide developers with a webhook

### ISSUE THREAD

**Issue by frgfm** [pyronear/pyro-api#145]
In order to send notifications on multiple systems based on alert raising on the API-side, we need to provide developers with a webhook option. Another front-end service of pyronear is already in need for this feature cf. https://github.com/pyronear/pyro-platform/issues/38

## Implementation suggestion
Fortunately, FastAPI [callbacks](https://fastapi.tiangolo.com/advanced/openapi-callbacks/) seem to be quite appropriate for this use case. However, I'm not exactly sure how to make a webhook available using that.

**Comment by frgfm** [comment]
So I checked a few resources over the past few days and here is how I envision the implementation:
a webhook = implementing a callback POST to an external URL simply put

Now back to our needs, for now I suggest:
- adding a webhook table, only accessible to admins, that have the following fields: `id`, `callback` (on which callback should this be triggered), `url` (the URL to which we'll make the POST request)
- set a `alert_notification` callback on the alert creation routes
- let admin set a webhook to the platform (i.e. for each service that needs a webhook, we simply set it ourselves)
- make the platform flask server able to receive this POST request and process it correctly

Any thoughts @pyronear/back-end ?

**Comment by florianriche** [comment]
I read the doc, seems to fit exactly our need indeed.

Not sure I understand why you would need a webhook table hook?
Is it the scenario you envision: The alert_notification callback, when called, look at the URLs in the webhook table it should call and then send the notification to them? Is that so?

**Comment by florianriche** [comment]
Or how about adding it in the `.env` file?
Do we really expect to have fluctuating Urls?

This design can work but I don't understand the need behind it?

**Comment by frgfm** [comment]
Well, let's say we migrate a service that needs a webhook: we simply update the table with an HTTP request with our admin token. With your suggestion, we either have to modify the secret on a PaaS, or modify a file on a IaaS.

I would prefer to go with your suggestion but I'm having doubts about the flexibility of this option. How do you see things if the webhooks change? (let's bear in mind that in months, we might have to add webhooks for each firefighter department system if they're not using our platform)

**Comment by florianriche** [comment]
I had not in mind that we could send the callbacks to other systems than our own. Thanks for the clarification
