### ISSUE TITLE
[test] Some bugs aren't caught up with our unittests

### ISSUE THREAD

**Issue by frgfm** [pyronear/pyro-api#17]
In #13 a small issue was introduced, that wasn't caught up by unittests.
Fortunately, @jeanpasquier75 noticed it and it's being solved in #16. But this raises the question about how we should design our unittests

Any thoughts @florianriche @jeanpasquier75 @fe51 ?

- [x] Update current unittests to get a testing situation as close as possible from production (#33)
- [x] Adding super-user creation mean (#26)

**Comment by florianriche** [comment]
I would assume we could create a dedicated test Class to test the CRUD behavior as well as the fact that the DB constraints are respected: e.g by inspiring ourselves from https://xvrdm.github.io/2017/07/03/testing-flask-sqlalchemy-database-with-pytest/ or https://stackoverflow.com/questions/14719507/unit-tests-for-query-in-sqlalchemy 

In addition, a E2E test (user creation, user_auth, device creation ....) would catch some issues too.

**Comment by frgfm** [comment]
This is now a priority:
I just found out that we have a typo in the device route https://github.com/pyronear/pyro-api/blob/master/src/app/api/routes/devices.py#L51, that should raise an error whenever we call the route.
This was not caught by the unittests because of our lazy monkeypatching. I'll dive into improving the unittests

@florianriche you might be the one with the best knowledge about authentication. Would you mind drafting consecutive route + payload to get a full end-to-end script?

**Comment by frgfm** [comment]
Changing the release target to 0.1.1 for the last part (end-to-end script)
