### ISSUE TITLE
[client][Retrieve Token] Issues passing creds with Content Type "application/x-www-form-urlencoded"

### ISSUE THREAD

**Issue by fe51** [pyronear/pyro-api#214]
Hi there, 

Using the api client, I have an issue when retrieving token ( in the frame of the installation of the newest test tower in Ardeche)

With correct creds (tested at https://api.pyronear.org/docs ), it basically works with some creds, and not with others !

At first, I thought it might be due to the encoding of the characters, as "application/x-www-form-urlencoded" as Content type [is not recommended to send text with non ASCII characters](https://www.microfocus.com/documentation/idol/IDOL_12_0/MediaServer/Guides/html/English/Content/Shared_Admin/_ADM_POST_requests.htm), in the request headers. 

Hence, switching from request with application/x-www-form-urlencoded to a "classic" post request with a json data, solves the issue.
However I realise that this solution is fortuitous because creds tested do not contain non-ASCII characters 🤣 

So, to be pragmatic, why using content type application/x-www-form-urlencoded in the first place to [retrieve token](https://github.com/pyronear/pyro-api/blob/master/client/pyroclient/client.py#L95) ? 
Is there any specific reason ? Otherwise, this PR #215  could be useful to avoid the problem mentioned above

happy to discuss it ! 

If anyone has an explanation as to why this doesn't work, I'm interested (text encoding then decoding causing issues?)

**Comment by fe51** [comment]
@pyronear/back-end

**Comment by fe51** [comment]
@MateoLostanlen @Akilditu

**Comment by frgfm** [comment]
Oh now I understand: when I generate the creds for this, there were indeed perhaps rarer characters. So the encoding might be different from the swagger :+1: 

Let me take a look at the PR!
