### ISSUE TITLE
[docs] Add a tutorial/walkthrough to deploy everything on your own

### ISSUE THREAD

**Issue by frgfm** [pyronear/pyro-api#231]
It would be greatly beneficial for contributors to know how to orchestrate everything on their own. I suggest making a tutorial for this

**Comment by blenzi** [comment]
The README suggests that cloning the package and calling `make run` should start the API but `curl http://localhost:8080/docs` returns `Empty reply from server`. If something else is needed, it would be good to mention it in the README

**Comment by frgfm** [comment]
Hi @blenzi :wave:

I just tried again myself and the curl yields:
```
    <!DOCTYPE html>
    <html>
    <head>
    <link type="text/css" rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swagger-ui-dist@4/swagger-ui.css">
    <link rel="shortcut icon" href="https://fastapi.tiangolo.com/img/favicon.png">
    <title>Pyronear API - Swagger UI</title>
    </head>
    <body>
    <div id="swagger-ui">
    </div>
    <script src="https://cdn.jsdelivr.net/npm/swagger-ui-dist@4/swagger-ui-bundle.js"></script>
    <!-- `SwaggerUIBundle` is now available on the page -->
    <script>
    const ui = SwaggerUIBundle({
        url: '/openapi.json',
    "dom_id": "#swagger-ui",
"layout": "BaseLayout",
"deepLinking": true,
"showExtensions": true,
"showCommonExtensions": true,
oauth2RedirectUrl: window.location.origin + '/docs/oauth2-redirect',
    presets: [
        SwaggerUIBundle.presets.apis,
        SwaggerUIBundle.SwaggerUIStandalonePreset
        ],
    })
    </script>
    </body>
    </html>
    % 
```
You can also see that the GH CI is performing the same action and get an answer from curl, so I don't really know what caused this :shrug: 

Please open a GH issue with the docker logs to debug this :pray:

**Comment by RonanMorgan** [comment]
we can closed this one, no ?

**Comment by frgfm** [comment]
Correct, we're way more on a `docker compose up` instruction now than previously :+1:
