### ISSUE TITLE
[admin scope issue][media]

### ISSUE THREAD

**Issue by fe51** [pyronear/pyro-api#242]
Hi there, 

As a user with **admin scope**, I have encountered the following issue : 

I have been denied access on a route where I am supposed to have access rights

Indeed, I get a error **403** using the get route : `/media/{media_id}/url`
and the following msg : 
```
{
  "detail": "This access can't read resources from group_id=3"
}
```

I am available to provide further information if required, 
Thanks a lot :)

**Comment by frgfm** [comment]
Closed by #253
