### ISSUE TITLE
[scripts] Add script to create super user

### ISSUE THREAD

**Issue by fe51** [pyronear/pyro-api#26]
## Feature
Add script to create super user

## Motivation
After a possible deletion of the volume of the db, it would be convenient to have a script to create a super user.

## Pitch
We might add a new folder called scripts with a first one, adding a super user with admin scope.

**Comment by frgfm** [comment]
I don't think there will but make sure to check #17 to avoid PR duplication with @florianriche ;)
Having one script to create a super user will be useful even in production, and an end-to-end script is more for example and testing purposes

**Comment by florianriche** [comment]
I don't know if a script is the right way to init a superuser.
In the cookie-cutter of fastapi, there is a piece of code that is executed at launch time to create this superuser. If the script exists, isn't there a risk (albeit small) that the superuser is created multiple times?

```python
def init_db(db: Session) -> None:
    # Tables should be created with Alembic migrations
    # But if you don't want to use migrations, create
    # the tables un-commenting the next line
    # Base.metadata.create_all(bind=engine)
    user = crud.user.get_by_email(db, email=settings.FIRST_SUPERUSER)
    if not user:
        user_in = schemas.UserCreate(
            email=settings.FIRST_SUPERUSER,
            password=settings.FIRST_SUPERUSER_PASSWORD,
            is_superuser=True,
        )
        user = crud.user.create(db, obj_in=user_in)  # noqa: F841```

Up to discuss

**Comment by fe51** [comment]
Thanks for the feed back.
Indeed, the possibility to create at launch time might be a better way ! We would run init_db, similar function to the one in the cookie-cutter, just after database connection in main.py (and having the init_db func somewhere)? or, should we have a separate script for inits, a bit like in cookie cutter (https://github.com/tiangolo/full-stack-fastapi-postgresql/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/backend/app/app/initial_data.py) and run it in adding a command in the docker-compose file ? 


I agree with you, having a script could led to have multiples super user.

**Comment by frgfm** [comment]
Indeed, if it's possible to do this at initialization, that would be perfect!
Having a separate python module like in the cookie cutter would be good option I think :ok_hand:
