### ISSUE TITLE
Tests failing often due httpbin.org timeout

### ISSUE THREAD

**Issue by blenzi** [pyronear/pyro-api#273]
Many pytest jobs are failing with

```
    def test_post_request():
        response = post_request("https://httpbin.org/post")
>       assert response.status_code == 200
E       assert 504 == 200
E        +  where 504 = <Response [504]>.status_code
```

Is there an alternative site, could the timeout be increased or maybe this is tested indirectly elsewhere? @frgfm

**Comment by frgfm** [comment]
The easy fix is to increase the timeout, by passing the number of seconds to `post_request`. But it's already at 10sec, so it's strange that the request doesn't go through :thinking:

**Comment by frgfm** [comment]
No longer apply since #322
