### ISSUE TITLE
Grouping alerts 

### ISSUE THREAD

**Issue by MateoLostanlen** [pyronear/pyro-api#280]
Hi there,

I'm trying to understand why the grouping of alerts doesn't work. Maybe I'm misunderstanding but it seems to me that we should put a symbol <= [here](https://github.com/pyronear/pyro-api/blob/fa2624d48b7c4de638ea87a589b6f118960ec7f7/src/app/api/crud/alerts.py#L23) to have the alerts created within the last 30 minutes, right?

@frgfm @blenzi what do you think ?

**Comment by blenzi** [comment]
Hi @MateoLostanlen , I think `>=` is correct since `max_ts = now - 30 minutes` and this is querying previous alerts. A query with `<=` would return all previous alerts (not within the last 30 minutes).

**Comment by blenzi** [comment]
In the end the mechanism is working but the deployed version had the old value of 5 minutes. Closing
