### ISSUE TITLE
[accesses] The update_access route does not check that new login might already be taken

### ISSUE THREAD

**Issue by frgfm** [pyronear/pyro-api#30]
Upon access creation, there is a verification to avoid login duplication in the table. However when using the corresponding put method, if the user changes her/his login to another existing one, nothing will check for duplication.

**Comment by jeanpasquier75** [comment]
Hello here, I figured out that we may have unclear naming between `users.username` and `accesses.login`. This can be linked to this issue and discussed in the same time

To be sure: `accesses.login` is the unique identifier and `users.username` is an information without any constraint ?

In my opinion "username" often refers to a unique login identifier, what about renaming `users.username` into `users.full_name` or something similar ? 

What about adding a unique contraint to `accesses.login` at db level in addition to a check at software level ?

**Comment by fe51** [comment]
Hello there, I think you are right jean !
We should have one unique identifier, such as ```accesses.login``` . Then, the actual ```users.username`` `should be rename to avoid confusion, and just be a information about the user (Felix).

Also, in Security aspects, we then should only rely on ```accesses.login```, is that right ? (maybe that is already always the case)


About adding a unique contraint to accesses.login at db level in addition to a check at software level, I agree as well

**Comment by frgfm** [comment]
The best person to ask would be @florianriche I guess!
But to the best of my understanding, `users.username` and `devices.name` are both accepted values for `accesses.login`, they are passed down to verify login + password through the authentication.

At the moment, I highly disagree with adding anything close to actual personal information (such as full name) @jeanpasquier75 . This avoids introducing now ways to get us into troubles about personal data.

Adding a check that login is valid is a good and necessary thing to do in my opinion!

And for clarity of field naming, the best option I could see would be to do:
`users.username` --> `users.login`
`devices.name` --> `devices.login`
so that it is clear that this is a reference to the unique login.

**Comment by florianriche** [comment]
> The best person to ask would be @florianriche I guess!
> But to the best of my understanding, users.username and devices.name are both accepted values for accesses.login, they are passed down to verify login + password through the authentication.

That is indeed how it is working. I guess instead of username we could use the email but I think we should do that move when there will be production consideration about what infos we want to store.

I agree for the field renaming. The initial reason we used username was (I think) because that is what was used in the FastAPI tutorials. In addition, it is a standard field in the Oauth2 token (that part should not be altered) so it limited confusion.
