### ISSUE TITLE
Add a proxy url for the s3 media fetch

### ISSUE THREAD

**Issue by Nastaliss** [pyronear/pyro-api#300]
We should add a configuration to allow using a proxy instead of the real s3 url. 
The s3 url is sometimes flagged as malicious in some entreprise networks.

- [x] #287 
- [x] #293 
- [x] #294

**Comment by Nastaliss** [comment]
This is now deployed to the production  platform. 
![image](https://github.com/pyronear/pyro-api/assets/46960549/15bd9384-cca8-43f9-a297-9daa2e0ff3bd)
Please keep in mind that to trigger a refresh of the alerts you need to empty your session storage and refresh the page

**Comment by Nastaliss** [comment]
The configuration is passed as an env variable `S3_PROXY_URL` to the api. 
It replaces the original url with this url when passed. By passing an empty string or no value the original behavior is kept.

**Comment by frgfm** [comment]
To the best of my understanding, this is already taken care of :)
