### ISSUE TITLE
[docs] Adding summary and description for each route

### ISSUE THREAD

**Issue by frgfm** [pyronear/pyro-api#31]
Hey there,

I ended up discovering that we can add a summary and description using the route decorator + its docstring (cf. https://fastapi.tiangolo.com/tutorial/path-operation-configuration/#description-from-docstring). I believe it would be a good idea to document each route (one PR for each separate router file in https://github.com/pyronear/pyro-api/tree/master/src/app/api/routes for easier reviewing):
- [x] accesses (#78)
- [x] alerts (#78)
- [x] devices (#78)
- [x] events(#52)
- [x] installations (#78)
- [x] login (#60)
- [x] media (#41)
- [x] sites (#38)
- [x] users (#78)

Suggestions for documentation improvements are welcome!

**Comment by fe51** [comment]
I have discoverd this feature doing PR on examples, and this is indeed a good idea ! Nice suggestion !

**Comment by frgfm** [comment]
Thanks @fe51 for the heavy lifting!
