### ISSUE TITLE
[devices] Add a route to update the location of the current device

### ISSUE THREAD

**Issue by frgfm** [pyronear/pyro-api#32]
Currently, the API supports the update of location information for a given device provided admin scope. However, a device with GPS capabilities should be able to update its own location.

This might be a good occasion to add a route to update the location of the current_device!

**Comment by fe51** [comment]
Good idea ! 
From my understanding, in the device routes, a user can perform the update of the location of a device in its scopes. Is it right ?
Thus, do you suggest to update this route to have a possible update from device access itself? 
```python 
@router.post("/{device_id}/update-location", response_model=DeviceOut)
async def update_location(payload: DefaultPosition,
                          device_id: int = Path(..., gt=0),
                          user: UserRead = Security(get_current_user, scopes=["me"])):
    return await routing.update_location(devices, payload, device_id, user.id)
```

**Comment by frgfm** [comment]
Yes correct!
With the current route, a user can update (let's say manually) the location of her/his devices. But if the device were to have GSP capabilities, perhaps it would be good that the device can update its own location (similarly to the heartbeat route) :man_shrugging:
