### ISSUE TITLE
[installations] Adding a route to list of devices on a site at a given time

### ISSUE THREAD

**Issue by frgfm** [pyronear/pyro-api#49]
As per https://github.com/pyronear/pyro-platform/issues/19#issuecomment-731733564, we need to able to tell how many devices (list them would avoid creating another route later) are on a specific site at a given time.

Addind a route `/list-devices` in installations would be the best option in my opinion

**Comment by florianriche** [comment]
I think it is  a good first issue.
Do you mean to add the routes to sites or installations?

**Comment by frgfm** [comment]
Good point, @martin1tab you were looking for some PR yesterday I recon?

I think installation would be the best option here, yielding the list of `device_id` as an output.
And then if they need more information about each device, they can use GET on the device table?
