### ISSUE TITLE
[auth] Enabled authentication on the platform/for third party applications

### ISSUE THREAD

**Issue by frgfm** [pyronear/pyro-api#55]
Hey there,

As suggested in https://github.com/pyronear/pyro-platform/issues/19, the platform will need a way to verify the login of its users. We suggested earlier to do this through the API, but I'm not certain about the best way to do this?

Should we create a route in accesses, that would only verify someone's credentials? Or should we have them create a token and then use that for other interactions with the API?

**Comment by florianriche** [comment]
I think the usual flow is to check for the token validity and if it doesn't exist then send the user to a login page; it sounds the more natural flow to me.

**Comment by jeanpasquier75** [comment]
I guess the platform contain an authentication form (login/pwd) posting on the `login/access-token` route. Once authenticated each request must contain the Bearer token in its header (like we did in the pyroclient). One way to handle this in front-end is storing the token in a cookie, it seams straightforward with Flask: https://pythonbasics.org/flask-cookies/

The platform should also enable admins to manage the users: a form to add ones, a way to list existing users with info update, deletion, etc. Each action making the proposer call to the API (add -> `post users/`, list -> `get users/`, etc.)

It may contain also a page for the users to manage users themselves (update infos, password)

Moreover if one request gets a forbidden response (not authenticated, token expired, not enough permission, etc.) it should redirect to the authentication form (it is more a front-end discussion)

Does it make sense to you ?

**Comment by frgfm** [comment]
@jeanpasquier75 about your suggestion for user management, I do feel that we are mixing stuff. Having an API/DB management platform is indeed a useful tool we would love to get in the future. Perhaps having that in the same platform as the one handling wildfire alerts is an option, but we could also have them separate or use a fastapi plugin.

This issue, for the time being, is only about the wildfire management platform over here: https://github.com/pyronear/pyro-platform.

But I fully agree on storing the token in the cookies. So on our side, everything is already good I guess? Returning a token, which can be passed in the following requests. We only have to get a login page and pass the values to the route + cookie storing mechanism on the platform repo.

**Comment by jeanpasquier75** [comment]
Indeed I may have mixed platform features. Whatever, we are good in the backend side (once we'll be clear on scopes)

**Comment by frgfm** [comment]
Closing this since it appears we're all good on the back-end side of authentication :ok_hand:
