### ISSUE TITLE
[client] Extend API client features for platform demo

### ISSUE THREAD

**Issue by frgfm** [pyronear/pyro-api#61]
Following up on https://github.com/pyronear/pyro-platform/issues/19, the following features need to be added to the client:
- [ ] Read all devices within the scope of the user
- [ ] Read the sites
- [ ] Read the list of device IDs of a given site at a given time (which ongoing on the API-side in #49)
- [ ] Read the alerts (while we don't have a webhook)
- [ ] Download the frame (media) linked to an alert

Considering the scopes of several routes are going to change (more restricted) with #45, this is all the more important since, if they are able to use GET on some routes without authentication, this might not be true in the future!

**Comment by Akilditu** [comment]
Thanks for this issue @frgfm !

Adding to the needs the ability to access the medias (frames) that triggered the alerts as we will display them in the platform (let's say at least on frame per alert for 1.0)

**Comment by florianriche** [comment]
I am starting a PR to add the functions to the Client; stop me if somebody already started working on it !

**Comment by florianriche** [comment]
For the last point, shall the API returns a real media or just the bucket_key to retrieve the image (from Carnot computing buckets)?

To me, it seems it would be a big load to put on the API to retrieve the images.

Or are we saying it is the API Client's  job to retrieve those medias? In that case it's fine by me.

**Comment by Akilditu** [comment]
That's a good point. 

Maybe easier for demo that API handle this
