### ISSUE TITLE
[Alerts] Acknowledge and close an alert

### ISSUE THREAD

**Issue by florianriche** [pyronear/pyro-api#63]
We have no route, for now, to specify an alert has been acknowledged and no way for a user to say an alert is complete.

The routes to do that should be quite straightforward.
One should also add functions to access those routes in the client.

**Side note:**
It also raises the question of how to interact with the events? I am not sure I clearly understand what they are supposed to do.

**Comment by frgfm** [comment]
Just thought about a tricky question: let's say we create a acknowledgement route, who should be able to use it apart from admin?
It should be the recipient of the alert (firefighter stations / operational centers) but so far, we have not linked the alert to this :thinking: 

The core idea behind this is to ensure that the information we send is well received

**Comment by florianriche** [comment]
I guess the users that belong to the same "userGroup" (notion not yet created) of the device--that-raised-the-alert's owner?
