### ISSUE TITLE
[media] Add a CSP service for actual media upload

### ISSUE THREAD

**Issue by frgfm** [pyronear/pyro-api#84]
The current media upload only updates the key/path of the media, while it does not upload content for the moment.
Qarnot computing support should be added as a supported bucket service.

Here is the documentation for it: https://computing.qarnot.com/documentation/sdk-python/api/storage/storage.html

**Comment by martin1tab** [comment]
@frgfm Do you have the credentials to access Qarnot ? Thanks

**Comment by frgfm** [comment]
Sure, I'll share with you the API token!
