### ISSUE TITLE
[media] Reduce image download latency on client

### ISSUE THREAD

**Issue by frgfm** [pyronear/pyro-api#97]
Currently, when requesting an image through the client:
- the API accesses the media table to get the bucket path, and adds the CSP creds
- it downloads the image on the API server
- the client then download the byte content from the API server

So we at least get a double latency on content transfer. A more optimal solution would be:
- the API resolves the URL + creds for a CSP file download
- the client uses this information to directly download from CSP

We could expect ~50% drop in latency in doing so!

cc @florianriche @Akilditu

**Comment by florianriche** [comment]
Qarnot python lcient  doesn't allow to retrieve a URL. It will imply to dig into the Qarnot python source ode to get how they do it.
